// <auto-generated />
using System;
using ChatYourRestaurant.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatYourRestaurant.DataAccess.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20250118193528_AddSeeder")]
    partial class AddSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lettuce"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Caesar Dressing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Parmesan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Croutons"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mozzarella"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Basil"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Beef Patty"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Pickles"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bun"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Pasta"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Pancetta"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Parmesan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Parsley"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Quinoa"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Chickpeas"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Avocado"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Roasted Vegetables"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Tahini Dressing"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Naan"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Fish"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Fries"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Tartar Sauce"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Mango"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Soy Sauce"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Wasabi"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Ginger"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Ribs"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Barbecue Sauce"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Carrots"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Olives"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Red Onions"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Lemon-Oregano Dressing"
                        });
                });

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.IngredientMeal", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientId", "MealId");

                    b.HasIndex("MealId");

                    b.ToTable("IngredientMeal", (string)null);

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            MealId = 1
                        },
                        new
                        {
                            IngredientId = 2,
                            MealId = 1
                        },
                        new
                        {
                            IngredientId = 3,
                            MealId = 1
                        },
                        new
                        {
                            IngredientId = 4,
                            MealId = 1
                        },
                        new
                        {
                            IngredientId = 5,
                            MealId = 1
                        },
                        new
                        {
                            IngredientId = 6,
                            MealId = 2
                        },
                        new
                        {
                            IngredientId = 7,
                            MealId = 2
                        },
                        new
                        {
                            IngredientId = 8,
                            MealId = 2
                        },
                        new
                        {
                            IngredientId = 9,
                            MealId = 3
                        },
                        new
                        {
                            IngredientId = 1,
                            MealId = 3
                        },
                        new
                        {
                            IngredientId = 7,
                            MealId = 3
                        },
                        new
                        {
                            IngredientId = 10,
                            MealId = 3
                        },
                        new
                        {
                            IngredientId = 11,
                            MealId = 3
                        },
                        new
                        {
                            IngredientId = 12,
                            MealId = 3
                        },
                        new
                        {
                            IngredientId = 13,
                            MealId = 4
                        },
                        new
                        {
                            IngredientId = 14,
                            MealId = 4
                        },
                        new
                        {
                            IngredientId = 15,
                            MealId = 4
                        },
                        new
                        {
                            IngredientId = 16,
                            MealId = 4
                        },
                        new
                        {
                            IngredientId = 17,
                            MealId = 4
                        },
                        new
                        {
                            IngredientId = 18,
                            MealId = 5
                        },
                        new
                        {
                            IngredientId = 19,
                            MealId = 5
                        },
                        new
                        {
                            IngredientId = 20,
                            MealId = 5
                        },
                        new
                        {
                            IngredientId = 21,
                            MealId = 5
                        },
                        new
                        {
                            IngredientId = 22,
                            MealId = 5
                        },
                        new
                        {
                            IngredientId = 23,
                            MealId = 6
                        },
                        new
                        {
                            IngredientId = 24,
                            MealId = 6
                        },
                        new
                        {
                            IngredientId = 25,
                            MealId = 6
                        },
                        new
                        {
                            IngredientId = 26,
                            MealId = 6
                        },
                        new
                        {
                            IngredientId = 27,
                            MealId = 7
                        },
                        new
                        {
                            IngredientId = 28,
                            MealId = 7
                        },
                        new
                        {
                            IngredientId = 29,
                            MealId = 7
                        },
                        new
                        {
                            IngredientId = 30,
                            MealId = 8
                        },
                        new
                        {
                            IngredientId = 20,
                            MealId = 8
                        },
                        new
                        {
                            IngredientId = 31,
                            MealId = 8
                        },
                        new
                        {
                            IngredientId = 32,
                            MealId = 8
                        },
                        new
                        {
                            IngredientId = 33,
                            MealId = 8
                        },
                        new
                        {
                            IngredientId = 34,
                            MealId = 8
                        },
                        new
                        {
                            IngredientId = 35,
                            MealId = 9
                        },
                        new
                        {
                            IngredientId = 36,
                            MealId = 9
                        },
                        new
                        {
                            IngredientId = 1,
                            MealId = 9
                        },
                        new
                        {
                            IngredientId = 37,
                            MealId = 9
                        },
                        new
                        {
                            IngredientId = 30,
                            MealId = 10
                        },
                        new
                        {
                            IngredientId = 7,
                            MealId = 10
                        },
                        new
                        {
                            IngredientId = 38,
                            MealId = 10
                        },
                        new
                        {
                            IngredientId = 11,
                            MealId = 10
                        },
                        new
                        {
                            IngredientId = 39,
                            MealId = 10
                        },
                        new
                        {
                            IngredientId = 40,
                            MealId = 10
                        });
                });

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Crispy romaine lettuce, grilled chicken, and Caesar dressing topped with parmesan and croutons.",
                            Name = "Grilled Chicken Caesar Salad",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic pizza topped with fresh mozzarella, tomatoes, and basil on a thin crust.",
                            Name = "Margherita Pizza",
                            Price = 10.50m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Juicy beef patty with lettuce, tomato, pickles, and cheddar cheese on a toasted bun.",
                            Name = "Beef Burger",
                            Price = 9.75m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Creamy pasta with pancetta, egg, and parmesan, garnished with parsley.",
                            Name = "Spaghetti Carbonara",
                            Price = 13.45m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A nutritious mix of quinoa, chickpeas, avocado, and roasted vegetables with a tahini dressing.",
                            Name = "Vegan Buddha Bowl",
                            Price = 11.25m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tender chicken in a spiced tomato-based sauce served with basmati rice and naan.",
                            Name = "Chicken Tikka Masala",
                            Price = 14.00m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Crispy battered fish served with golden fries and tartar sauce.",
                            Name = "Fish and Chips",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Assorted vegetable sushi rolls with soy sauce, wasabi, and pickled ginger.",
                            Name = "Vegetarian Sushi Platter",
                            Price = 15.00m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Slow-cooked ribs smothered in tangy barbecue sauce, served with coleslaw.",
                            Name = "BBQ Ribs",
                            Price = 17.95m
                        },
                        new
                        {
                            Id = 10,
                            Description = "A refreshing mix of cucumbers, tomatoes, olives, feta cheese, and red onions with a lemon-oregano dressing.",
                            Name = "Greek Salad",
                            Price = 8.75m
                        });
                });

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.MealQuantity", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("MealId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("MealQuantity");
                });

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.IngredientMeal", b =>
                {
                    b.HasOne("ChatYourRestaurant.Domain.Common.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatYourRestaurant.Domain.Common.Models.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.MealQuantity", b =>
                {
                    b.HasOne("ChatYourRestaurant.Domain.Common.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatYourRestaurant.Domain.Common.Models.Order", "Order")
                        .WithMany("MealQuantities")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ChatYourRestaurant.Domain.Common.Models.Order", b =>
                {
                    b.Navigation("MealQuantities");
                });
#pragma warning restore 612, 618
        }
    }
}
